name: Check

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: dotnet clean
      run: dotnet clean --configuration Release && dotnet nuget locals all --clear
    - name: Restore dependencies
      run: dotnet restore

    # environmental variables
    - run: echo "PROJ=./WolvenManager.UI/WolvenManager.UI.csproj" >> $env:GITHUB_ENV
    - run: echo "OUT=./publish/full" >> $env:GITHUB_ENV
    - run: echo "NAME=WolvenManager" >> $env:GITHUB_ENV
    - name: Get version
      uses: naminodarie/get-net-sdk-project-versions-action@v1
      id: get-version
      with:
        proj-path:  ${{env.PROJ}}
    - run: echo "VERSION=${{steps.get-version.outputs.version}}" >> $env:GITHUB_ENV

    # Test building an publishing
    - name: Build
      run: dotnet build ${{env.PROJ}} --no-restore
    - name: Publish
      run: dotnet publish ${{env.PROJ}} -o ${{env.OUT}} --no-self-contained --no-restore -r win-x64 -c Release -f net5.0-windows 

    # PORTABLE
    - uses: actions/upload-artifact@v2
      with:
        name: ${{env.NAME}}-${{env.VERSION}}.zip
        path: ${{env.OUT}}

