name: Release

on:
  push:
    tags:
    - '*'

jobs:
  
  release:
    runs-on: windows-latest
    outputs:
      version: ${{steps.get-version.outputs.version}}

    steps:
    # setup  
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
      
      
    # Publish app
    - run: dotnet publish -o .\publish -c Release
    - run: Compress-Archive -Path .\publish\* -DestinationPath .\WolvenManager.zip

    # installer
    # - run: .\InnoSetup\ISCC\ISCC.exe /O"publish" /dMyAppBaseDir="..\publish\full\" .\InnoSetup\installer.iss

    # RELEASE
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        draft: true
        generateReleaseNotes: true
        artifacts: "WolvenManager.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        
  
  
  
  
  
  
