name: Release

on:
  workflow_dispatch:

jobs:
  
  release:
    runs-on: windows-latest
    outputs:
      version: ${{steps.get-version.outputs.version}}

    steps:
    # setup
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: dotnet clean
      run: dotnet clean --configuration Release && dotnet nuget locals all --clear
    - name: Restore dependencies
      run: dotnet restore
      
    # environmental variables
    - run: echo "PROJ=./WolvenManager.UI/WolvenManager.UI.csproj" >> $env:GITHUB_ENV
    - run: echo "OUT=./publish/full" >> $env:GITHUB_ENV
    - run: echo "FINALOUT=./publish" >> $env:GITHUB_ENV
    - run: echo "NAME=WolvenManager" >> $env:GITHUB_ENV
    - name: Get version
      uses: naminodarie/get-net-sdk-project-versions-action@v1
      id: get-version
      with:
        proj-path:  ${{env.PROJ}}
    - run: echo "VERSION=${{steps.get-version.outputs.version}}" >> $env:GITHUB_ENV
    - run: echo "PORTABLE=${{env.NAME}}-${{env.VERSION}}.zip" >> $env:GITHUB_ENV
    - run: echo "INSTALLER=${{env.NAME}}-installer-${{env.VERSION}}.exe" >> $env:GITHUB_ENV
    - run: echo "MANIFEST=manifest.json" >> $env:GITHUB_ENV
      
    # Publish app
    - run: dotnet publish ${{env.PROJ}} -o ${{env.OUT}} --no-self-contained --no-restore -r win-x64 -c Release -f net5.0-windows

    # Create assets
    - run: ${{env.OUT}}/WolvenManager.Installer.exe create -a ${{env.OUT}}\WolvenManager.UI.exe -o .\publish
    - run: .\InnoSetup\ISCC\ISCC.exe /O"publish" /dMyAppBaseDir="..\publish\full\" .\InnoSetup\installer.iss
    - run: ${{env.OUT}}/WolvenManager.Installer.exe manifest -a ${{env.OUT}}\WolvenManager.UI.exe -i .\publish -o .\publish

    # PORTABLE
    - uses: actions/upload-artifact@v2
      with:
        name: ${{env.PORTABLE}}
        path: ${{env.FINALOUT}}/${{env.PORTABLE}}
    # INSTALLER
    - uses: actions/upload-artifact@v2
      with:
        name: ${{env.INSTALLER}}
        path: ${{env.FINALOUT}}/${{env.INSTALLER}}
    # MANIFEST
    - uses: actions/upload-artifact@v2
      with:
        name: ${{env.MANIFEST}}
        path: ${{env.FINALOUT}}/${{env.MANIFEST}}
       
    # RELEASE
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: ./CHANGELOG.md
        files: |
          ${{env.FINALOUT}}/${{env.PORTABLE}}
          ${{env.FINALOUT}}/${{env.INSTALLER}}
          ${{env.FINALOUT}}/${{env.MANIFEST}}
        draft: true
        name: ${{env.NAME}} v${{env.VERSION}}
        tag_name: "${{env.VERSION}}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  
  
  
  
  
  
